s=1%1%
2.21
"Q:\Planejamento de Transportes\Sistemas\EMME\Simulacoes SPV\20200512-DU-ABR 2020 (COVID)\headways\hdw-h%1%.211"
1
2


3.11
"Q:\Planejamento de Transportes\Sistemas\EMME\Simulacoes SPV\20200512-DU-ABR 2020 (COVID)\matrizes\20200401-OD%1%.311"
1

3.12
3
mf2%1%
2
all
all
0
yes
9

5.32
2
mf1%1%
tp
2
1
2
0.2
0.05
2
1
1
ui2
1
2
2
ui3
1
1
0
1
1

0

yes
mf2%1%
no
2
"Q:\Planejamento de Transportes\Sistemas\EMME\Simulacoes SPV\20200512-DU-ABR 2020 (COVID)\logs\log_assign_hora%1%.txt"

