reports=?
plots=?
batchout=?
batchin=?
~<"Q:\Planejamento de Transportes\Sistemas\EMME\Simulacoes SPV\20200512-DU-ABR 2020 (COVID)\macros\deletar_cenarios.mac"
~<"Q:\Planejamento de Transportes\Sistemas\EMME\Simulacoes SPV\20200512-DU-ABR 2020 (COVID)\macros\copiar_cenarios.mac"
~<"Q:\Planejamento de Transportes\Sistemas\EMME\Simulacoes SPV\20200512-DU-ABR 2020 (COVID)\macros\rodar_cenarios.mac"
~<"Q:\Planejamento de Transportes\Sistemas\EMME\Simulacoes SPV\20200512-DU-ABR 2020 (COVID)\macros\rodar_relatorios.mac"
q
